version: 2
jobs:
  build-arduino-default:
    machine: true
    steps:
      - checkout
      
      - run:
          name: Make scripts executable 
          command: sudo chmod -R +x ./.circleci/*.sh
          
      - run:
          name: Install
          command: ./.circleci/install_arduino.sh
          
      - run:
          name: Build
          command: ./.circleci/run_arduino.sh
      - run:
          name: Tests
          command: ./.circleci/run_tests.sh
      - store_artifacts:
          path: /tmp/test_output.txt
          destination: test_output

workflows:
  version: 2
  build:
    jobs:
      - build-arduino-default
